package cpp

import (
	"bytes"
	"fmt"
	"strings"

	"lcode/pkg/ast"
)

// Generator C++17 代码生成器
type Generator struct {
	buf         bytes.Buffer
	indent      int
	hasMainFunc bool
}

// NewGenerator 创建生成器
func NewGenerator() *Generator {
	return &Generator{}
}

// Generate 将 Lcode AST 翻译为现代 C++17 源代码
func (g *Generator) Generate(prog *ast.Program) (string, error) {
	g.buf.Reset()
	g.indent = 0
	g.hasMainFunc = false

	// 1. 检查是否存在 main 函数定义
	for _, decl := range prog.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok && fn.Name.Value == "main" {
			g.hasMainFunc = true
			break
		}
	}

	// 2. 生成文件头和头文件包含
	g.writeln("// ==============================================================================")
	g.writeln("//  Generated by Lcode Compiler (C++17 Backend)")
	g.writeln("//  纯 Go 编译器前端自动转译生成")
	g.writeln("// ==============================================================================")
	g.writeln("#include <iostream>")
	g.writeln("#include <string>")
	g.writeln("#include <cstdint>")
	g.writeln("#include <cmath>")
	g.writeln("#include <vector>")
	g.writeln("#include \"lcode_cpp.hpp\"")
	g.writeln("")

	// 3. 前置函数声明 (Forward Declarations)
	for _, decl := range prog.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok {
			g.generateFuncSignature(fn)
			g.writeln(";")
		}
	}
	g.writeln("")

	// 4. 函数具体实现
	for _, decl := range prog.Decls {
		if fn, ok := decl.(*ast.FuncDecl); ok {
			if err := g.generateFunc(fn); err != nil {
				return "", err
			}
			g.writeln("")
		}
	}

	// 5. 生成 C++ main 入口
	g.writeln("int main(int argc, char* argv[]) {")
	g.indent++
	g.writeln("// 顶层全局语句执行")
	for _, stmt := range prog.Stmts {
		if err := g.generateStmt(stmt); err != nil {
			return "", err
		}
	}

	if g.hasMainFunc {
		g.writeln("lcode_user_main();")
	}

	g.writeln("return 0;")
	g.indent--
	g.writeln("}")

	return g.buf.String(), nil
}

func (g *Generator) generateFuncSignature(fn *ast.FuncDecl) {
	retType := "void"
	if fn.ReturnType != nil {
		retType = toCppType(fn.ReturnType.Name)
	}

	fnName := fn.Name.Value
	if fnName == "main" {
		fnName = "lcode_user_main"
	}

	params := make([]string, 0, len(fn.Params))
	for _, p := range fn.Params {
		pType := "int64_t"
		if p.Type != nil {
			pType = toCppType(p.Type.Name)
		}
		params = append(params, fmt.Sprintf("%s %s", pType, p.Name.Value))
	}

	g.writeIndent()
	g.buf.WriteString(fmt.Sprintf("%s %s(%s)", retType, fnName, strings.Join(params, ", ")))
}

func (g *Generator) generateFunc(fn *ast.FuncDecl) error {
	g.generateFuncSignature(fn)
	g.buf.WriteString(" {\n")
	g.indent++

	for _, stmt := range fn.Body.Statements {
		if err := g.generateStmt(stmt); err != nil {
			return err
		}
	}

	g.indent--
	g.writeIndent()
	g.buf.WriteString("}\n")
	return nil
}

func (g *Generator) generateStmt(stmt ast.Stmt) error {
	switch s := stmt.(type) {
	case *ast.VarDeclStmt:
		g.writeIndent()
		typeStr := "auto"
		if s.Type != nil {
			typeStr = toCppType(s.Type.Name)
		}
		qualifier := "const "
		if s.IsMut {
			qualifier = ""
		}
		valStr := "0"
		if s.Value != nil {
			v, err := g.generateExpr(s.Value)
			if err != nil {
				return err
			}
			valStr = v
		}
		g.buf.WriteString(fmt.Sprintf("%s%s %s = %s;\n", qualifier, typeStr, s.Name.Value, valStr))

	case *ast.AssignStmt:
		g.writeIndent()
		leftStr, err := g.generateExpr(s.Left)
		if err != nil {
			return err
		}
		rightStr, err := g.generateExpr(s.Right)
		if err != nil {
			return err
		}
		g.buf.WriteString(fmt.Sprintf("%s %s %s;\n", leftStr, s.Operator, rightStr))

	case *ast.IfStmt:
		g.writeIndent()
		condStr, err := g.generateExpr(s.Condition)
		if err != nil {
			return err
		}
		g.buf.WriteString(fmt.Sprintf("if (%s) {\n", condStr))
		g.indent++
		for _, subStmt := range s.Consequence.Statements {
			if err := g.generateStmt(subStmt); err != nil {
				return err
			}
		}
		g.indent--
		g.writeIndent()
		g.buf.WriteString("}")

		if s.Alternative != nil {
			if block, ok := s.Alternative.(*ast.BlockStmt); ok {
				g.buf.WriteString(" else {\n")
				g.indent++
				for _, subStmt := range block.Statements {
					if err := g.generateStmt(subStmt); err != nil {
						return err
					}
				}
				g.indent--
				g.writeIndent()
				g.buf.WriteString("}")
			} else {
				g.buf.WriteString(" else ")
				if err := g.generateStmt(s.Alternative); err != nil {
					return err
				}
			}
		}
		g.buf.WriteString("\n")

	case *ast.WhileStmt:
		g.writeIndent()
		condStr, err := g.generateExpr(s.Condition)
		if err != nil {
			return err
		}
		g.buf.WriteString(fmt.Sprintf("while (%s) {\n", condStr))
		g.indent++
		for _, subStmt := range s.Body.Statements {
			if err := g.generateStmt(subStmt); err != nil {
				return err
			}
		}
		g.indent--
		g.writeIndent()
		g.buf.WriteString("}\n")

	case *ast.ReturnStmt:
		g.writeIndent()
		if s.ReturnValue != nil {
			valStr, err := g.generateExpr(s.ReturnValue)
			if err != nil {
				return err
			}
			g.buf.WriteString(fmt.Sprintf("return escape_return(%s);\n", valStr))
		} else {
			g.buf.WriteString("return;\n")
		}

	case *ast.ExprStmt:
		exprStr, err := g.generateExpr(s.Expression)
		if err != nil {
			return err
		}
		g.writeIndent()
		g.buf.WriteString(exprStr + ";\n")

	case *ast.BlockStmt:
		g.writeIndent()
		g.buf.WriteString("{\n")
		g.indent++
		g.writeIndent()
		g.buf.WriteString("ScopeGuard _scope_raii;\n")
		for _, subStmt := range s.Statements {
			if err := g.generateStmt(subStmt); err != nil {
				return err
			}
		}
		g.indent--
		g.writeIndent()
		g.buf.WriteString("}\n")
	}
	return nil
}

func (g *Generator) generateExpr(expr ast.Expr) (string, error) {
	if expr == nil {
		return "", nil
	}

	switch e := expr.(type) {
	case *ast.IntegerLiteral:
		return fmt.Sprintf("%dLL", e.Value), nil

	case *ast.FloatLiteral:
		return fmt.Sprintf("%f", e.Value), nil

	case *ast.StringLiteral:
		return fmt.Sprintf("std::string(%q)", e.Value), nil

	case *ast.BooleanLiteral:
		if e.Value {
			return "true", nil
		}
		return "false", nil

	case *ast.Identifier:
		return e.Value, nil

	case *ast.GroupedExpr:
		inner, err := g.generateExpr(e.Expression)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s)", inner), nil

	case *ast.UnaryExpr:
		right, err := g.generateExpr(e.Right)
		if err != nil {
			return "", err
		}
		if e.Operator == "&" {
			// Rust 风格借用标记 (&x)：向 C++ 传递被借用的底层对象句柄
			return right, nil
		}
		if e.Operator == "*" {
			return fmt.Sprintf("(*%s)", right), nil
		}
		return fmt.Sprintf("(%s%s)", e.Operator, right), nil

	case *ast.BinaryExpr:
		left, err := g.generateExpr(e.Left)
		if err != nil {
			return "", err
		}
		right, err := g.generateExpr(e.Right)
		if err != nil {
			return "", err
		}
		return fmt.Sprintf("(%s %s %s)", left, e.Operator, right), nil

	case *ast.CallExpr:
		ident, ok := e.Function.(*ast.Identifier)
		if !ok {
			return "", fmt.Errorf("暂不支持复杂调用目标")
		}

		args := make([]string, 0, len(e.Arguments))
		for _, arg := range e.Arguments {
			aStr, err := g.generateExpr(arg)
			if err != nil {
				return "", err
			}
			args = append(args, aStr)
		}

		if ident.Value == "println" || ident.Value == "p" || ident.Value == "pln" || ident.Value == "prn" {
			return fmt.Sprintf("lcode::io::println(%s)", strings.Join(args, ", ")), nil
		}
		if ident.Value == "print" || ident.Value == "prin" || ident.Value == "pri" || ident.Value == "pr" {
			return fmt.Sprintf("lcode::io::print(%s)", strings.Join(args, ", ")), nil
		}

		// 如果调用的用户自定义 main
		callName := ident.Value
		if callName == "main" {
			callName = "lcode_user_main"
		}

		return fmt.Sprintf("%s(%s)", callName, strings.Join(args, ", ")), nil
	}

	return "", fmt.Errorf("未知表达式类型: %T", expr)
}

func (g *Generator) writeIndent() {
	for i := 0; i < g.indent; i++ {
		g.buf.WriteString("    ")
	}
}

func (g *Generator) writeln(s string) {
	if s == "" {
		g.buf.WriteString("\n")
		return
	}
	g.writeIndent()
	g.buf.WriteString(s)
	g.buf.WriteString("\n")
}

func toCppType(lcodeType string) string {
	switch lcodeType {
	case "int":
		return "int64_t"
	case "float":
		return "double"
	case "string":
		return "std::string"
	case "bool":
		return "bool"
	case "void":
		return "void"
	default:
		return "auto"
	}
}
